# Generated by Django 5.1.2 on 2024-11-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linha',
            name='rota',
        ),
        migrations.AddField(
            model_name='linha',
            name='descricao',
            field=models.TextField(default='Descrição padrão'),
        ),
        migrations.AddField(
            model_name='rota',
            name='ponto_fim',
            field=models.CharField(default='Ponto de Fim Padrão', max_length=100),
        ),
        migrations.AddField(
            model_name='rota',
            name='ponto_inicio',
            field=models.CharField(default='Ponto de Início Padrão', max_length=100),
        ),
    ]
