# Generated by Django 5.1.2 on 2024-11-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreamento', '0002_remove_linha_rota_linha_descricao_rota_ponto_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onibus',
            name='linha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onibuss', to='rastreamento.linha'),
        ),
    ]
