# Generated by Django 5.1.2 on 2024-11-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreamento', '0003_onibus_linha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linha',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='linha',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='PontoOnibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('linhas', models.ManyToManyField(related_name='pontos_onibus', to='rastreamento.linha')),
            ],
        ),
    ]
